[node0121.palmetto.clemson.edu:08552] mca: base: component_find: unable to open /software/openmpi/1.10.7_gcc/lib/openmpi/mca_btl_openib: libibverbs.so.1: cannot open shared object file: No such file or directory (ignored)
[node1806.palmetto.clemson.edu:09862] mca: base: component_find: unable to open /software/openmpi/1.10.7_gcc/lib/openmpi/mca_btl_openib: libibverbs.so.1: cannot open shared object file: No such file or directory (ignored)
[node1832.palmetto.clemson.edu:36784] mca: base: component_find: unable to open /software/openmpi/1.10.7_gcc/lib/openmpi/mca_btl_openib: libibverbs.so.1: cannot open shared object file: No such file or directory (ignored)
[node1882.palmetto.clemson.edu:58721] mca: base: component_find: unable to open /software/openmpi/1.10.7_gcc/lib/openmpi/mca_btl_openib: libibverbs.so.1: cannot open shared object file: No such file or directory (ignored)
[node0200.palmetto.clemson.edu:40959] mca: base: component_find: unable to open /software/openmpi/1.10.7_gcc/lib/openmpi/mca_btl_openib: libibverbs.so.1: cannot open shared object file: No such file or directory (ignored)
[node0046.palmetto.clemson.edu:93758] mca: base: component_find: unable to open /software/openmpi/1.10.7_gcc/lib/openmpi/mca_btl_openib: libibverbs.so.1: cannot open shared object file: No such file or directory (ignored)
[node1810.palmetto.clemson.edu:03524] mca: base: component_find: unable to open /software/openmpi/1.10.7_gcc/lib/openmpi/mca_btl_openib: libibverbs.so.1: cannot open shared object file: No such file or directory (ignored)
[node0139.palmetto.clemson.edu:26928] mca: base: component_find: unable to open /software/openmpi/1.10.7_gcc/lib/openmpi/mca_btl_openib: libibverbs.so.1: cannot open shared object file: No such file or directory (ignored)
[node1881.palmetto.clemson.edu:60897] mca: base: component_find: unable to open /software/openmpi/1.10.7_gcc/lib/openmpi/mca_btl_openib: libibverbs.so.1: cannot open shared object file: No such file or directory (ignored)
[node0175.palmetto.clemson.edu:63024] mca: base: component_find: unable to open /software/openmpi/1.10.7_gcc/lib/openmpi/mca_btl_openib: libibverbs.so.1: cannot open shared object file: No such file or directory (ignored)
[node1883.palmetto.clemson.edu:121946] mca: base: component_find: unable to open /software/openmpi/1.10.7_gcc/lib/openmpi/mca_btl_openib: libibverbs.so.1: cannot open shared object file: No such file or directory (ignored)
[node1805.palmetto.clemson.edu:77778] mca: base: component_find: unable to open /software/openmpi/1.10.7_gcc/lib/openmpi/mca_btl_openib: libibverbs.so.1: cannot open shared object file: No such file or directory (ignored)
[node1811.palmetto.clemson.edu:09725] mca: base: component_find: unable to open /software/openmpi/1.10.7_gcc/lib/openmpi/mca_btl_openib: libibverbs.so.1: cannot open shared object file: No such file or directory (ignored)
[node0145.palmetto.clemson.edu:54695] mca: base: component_find: unable to open /software/openmpi/1.10.7_gcc/lib/openmpi/mca_btl_openib: libibverbs.so.1: cannot open shared object file: No such file or directory (ignored)
[node1808.palmetto.clemson.edu:18125] mca: base: component_find: unable to open /software/openmpi/1.10.7_gcc/lib/openmpi/mca_btl_openib: libibverbs.so.1: cannot open shared object file: No such file or directory (ignored)
[node0653.palmetto.clemson.edu:101019] mca: base: component_find: unable to open /software/openmpi/1.10.7_gcc/lib/openmpi/mca_btl_openib: libibverbs.so.1: cannot open shared object file: No such file or directory (ignored)
IOR-3.2.0: MPI Coordinated Test of Parallel I/O
Began               : Thu Oct 18 13:52:14 2018
Command line        : /home/jburto2/io-500-dev/bin/ior -r -R -C -Q 1 -g -G 27 -k -e -t 2m -b 131072m -F -a MPIIO -o /scratch1/jburto2/io500/datafiles/io500.2018.10.18-13.18.27/ior_easy/ior_file_easy -O stoneWallingStatusFile=/scratch1/jburto2/io500/datafiles/io500.2018.10.18-13.18.27/ior_easy/stonewall
Machine             : Linux node0046.palmetto.clemson.edu
TestID              : 0
StartTime           : Thu Oct 18 13:52:14 2018
Path                : /scratch1/jburto2/io500/datafiles/io500.2018.10.18-13.18.27/ior_easy
FS                  : 232.8 TiB   Used FS: 14.3%   Inodes: 4398046511104.0 Mi   Used Inodes: 0.0%

Options: 
api                 : MPIIO
apiVersion          : (3.0)
test filename       : /scratch1/jburto2/io500/datafiles/io500.2018.10.18-13.18.27/ior_easy/ior_file_easy
access              : file-per-process
type                : independent
segments            : 1
ordering in a file  : sequential
ordering inter file : constant task offset
task offset         : 1
tasks               : 16
clients per node    : 1
repetitions         : 1
xfersize            : 2 MiB
blocksize           : 128 GiB
aggregate filesize  : 2 TiB

Results: 

access    bw(MiB/s)  block(KiB) xfer(KiB)  open(s)    wr/rd(s)   close(s)   total(s)   iter
------    ---------  ---------- ---------  --------   --------   --------   --------   ----
[E 13:57:15.240358] job_time_mgr_expire: job time out: cancelling flow operation, job_id: 131.
[E 13:57:15.240465] fp_multiqueue_cancel: flow proto cancel called on 0x2f174f0
[E 13:57:15.240474] fp_multiqueue_cancel: I/O error occurred
[E 13:57:15.240482] handle_io_error: flow proto error cleanup started on 0x2f174f0: Operation cancelled (possibly due to timeout)
[E 13:57:15.240568] handle_io_error: flow proto 0x2f174f0 canceled 1 operations, will clean up.
[E 13:57:15.240581] bmi_to_mem_callback_fn: I/O error occurred
[E 13:57:15.240586] handle_io_error: flow proto 0x2f174f0 error cleanup finished: Operation cancelled (possibly due to timeout)
[E 13:57:15.240597] io_datafile_complete_operations: flow failed, retrying from msgpair
[E 14:04:56.353508] job_time_mgr_expire: job time out: cancelling flow operation, job_id: 229801.
[E 14:04:56.353617] fp_multiqueue_cancel: flow proto cancel called on 0x1f3b208
[E 14:04:56.353626] fp_multiqueue_cancel: I/O error occurred
[E 14:04:56.353634] handle_io_error: flow proto error cleanup started on 0x1f3b208: Operation cancelled (possibly due to timeout)
[E 14:04:56.353699] handle_io_error: flow proto 0x1f3b208 canceled 1 operations, will clean up.
[E 14:04:56.353711] bmi_to_mem_callback_fn: I/O error occurred
[E 14:04:56.353715] handle_io_error: flow proto 0x1f3b208 error cleanup finished: Operation cancelled (possibly due to timeout)
[E 14:04:56.353726] io_datafile_complete_operations: flow failed, retrying from msgpair
[E 14:08:09.078883] job_time_mgr_expire: job time out: cancelling flow operation, job_id: 504243.
[E 14:08:09.078997] fp_multiqueue_cancel: flow proto cancel called on 0x28d2218
[E 14:08:09.079006] fp_multiqueue_cancel: I/O error occurred
[E 14:08:09.079015] handle_io_error: flow proto error cleanup started on 0x28d2218: Operation cancelled (possibly due to timeout)
[E 14:08:09.079083] handle_io_error: flow proto 0x28d2218 canceled 1 operations, will clean up.
[E 14:08:09.079097] bmi_to_mem_callback_fn: I/O error occurred
[E 14:08:09.079102] handle_io_error: flow proto 0x28d2218 error cleanup finished: Operation cancelled (possibly due to timeout)
[E 14:08:09.079113] io_datafile_complete_operations: flow failed, retrying from msgpair
WARNING: Expected aggregate file size       = 2199023255552.
WARNING: Stat() of aggregate file size      = 1711108259840.
WARNING: Using actual aggregate bytes moved = 1711108259840.
read      1645.91    134217728  2048.00    0.505452   990.95     0.001773   991.45     0   
Max Read:  1645.91 MiB/sec (1725.86 MB/sec)

Summary of all tests:
Operation   Max(MiB)   Min(MiB)  Mean(MiB)     StdDev   Max(OPs)   Min(OPs)  Mean(OPs)     StdDev    Mean(s) Test# #Tasks tPN reps fPP reord reordoff reordrand seed segcnt   blksiz    xsize aggs(MiB)   API RefNum
read         1645.91    1645.91    1645.91       0.00     822.95     822.95     822.95       0.00  991.45164     0     16   1    1   1     1        1         0    0      1 137438953472  2097152 1631840.0 MPIIO      0
Finished            : Thu Oct 18 14:08:46 2018
